### PR TITLE
New file with fantastic tips!

### PR DESCRIPTION
**Pull request by shashwatsridhar**

### CODE REVIEW

**Review by rjurkus — CHANGES_REQUESTED** [review]
Please fix the typo "Evene smaller title"

**Comment by tobikausk** [comment]
I like!

**Comment by AlexVanMeegen** [comment]
@shashwatsridhar if you look at the changed files now, this is a bit messed up. Do you see a way to fix this? Besides, @Qkley is it fine now?

**Review by rjurkus — APPROVED** [review]
Excellent!

**Comment by rjurkus** [comment]
I cannot merge this since I do not have the write access to this repo

**Pull request merged**
